### ISSUE TITLE
能否将Clash运行文件单独出来？

### ISSUE THREAD

**Issue by sephiroth945** [Clash-Mini/Clash.Mini#10]
Clash.Mini目前打包了Clash.exe运行文件，请问能否单独出来？便于替换第三方的修改版本

**Comment by Clash-Mini** [comment]
@sephiroth945 哪种第三方？vless?

**Comment by sephiroth945** [comment]
支持vless的第三方是一种选择，不过我目前是没用到vless
另一个原因是官方更新版本可以直接替换

**Comment by Clash-Mini** [comment]
@sephiroth945 clash核心会和官方同步升级，这个倒不用担心

**Comment by sephiroth945** [comment]
好的，谢谢！

**Comment by RikudouPatrickstar** [comment]
支持将 Clash 内核独立出来

**Comment by Miroxyz** [comment]
独立出来吧，切换什么的都方便点
