### ISSUE TITLE
一个奈飞相关的小问题

### ISSUE THREAD

**Issue by MRDOCTOROO** [Clash-Mini/Clash.Mini#11]
在实测后发现使用支持奈飞的节点用clash.mini打开uwp版奈飞（已经启用回环）的时候会显示：Netflix 顯示「抱歉，與 Netflix 通訊發生問題。(T1-H1-W80072EFD)。使用相同节点换用clash for windows是能够正常进入到登录界面。

**Comment by Clash-Mini** [comment]
@MRDOCTOROO 好的，这边测试下
