### ISSUE TITLE
配置管理窗口，下拉菜单，点击“添加配置”项时，程序有极大概率崩溃退出

### ISSUE THREAD

**Issue by liuxb** [Clash-Mini/Clash.Mini#2]
1配置管理窗口，下拉菜单，点击“添加配置”项时，程序有极大概率崩溃退出
2能否把不同配置中的代理合并到一起使用？现在是同一时间只能使用一个配置中的代理，如果想用其他配置中代理，必须要启用其他配置。
谢谢。

**Comment by Clash-Mini** [comment]
1、请详细告知运行环境，系统版本等。目前暂无复现的情况，所以我会多做测试。
2、如果需要不同代理合并的话，请使用配置管理中「订阅转换」功能，可以把多个机场链接合并成单一配置文件。

**Comment by liuxb** [comment]
1 系统windows 10 1607 14393.4225 32bit，不过现在好像又没有了，我再看看。
2 问题解决。

再一个新请求：能否增加一个“重新载入配置”的功能，这样，手动修改根目录config.yaml文件后，可以重载配置并生效，不需要重新启动程序了。

**Comment by Clash-Mini** [comment]
@liuxb 配置管理，直接启用其他配置，就实时刷新了呢。

**Comment by Mazeorz** [comment]
> 1 系统windows 10 1607 14393.4225 32bit，不过现在好像又没有了，我再看看。
> 2 问题解决。
> 
> 再一个新请求：能否增加一个“重新载入配置”的功能，这样，手动修改根目录config.yaml文件后，可以重载配置并生效，不需要重新启动程序了。

把改后的配置放到profile文件夹中，直接启用就等于重新加载，不需要退出程序

**Comment by liuxb** [comment]
嗯明白了。
再一个，能不能改一下图标，任务栏托盘区的图标，现在的尺寸有点小颜色也太暗了，直连模式和规则模式的图标也没有区分。
