### ISSUE TITLE
Switch Profile更新后profile重复

### ISSUE THREAD

**Issue by sephiroth945** [Clash-Mini/Clash.Mini#29]
Switch Profile里面列表的profile有重复的情况，更新一次就多一组重复的
![无标题](https://user-images.githubusercontent.com/7221339/143802923-6d11051a-dde1-4b7a-8c64-da7eb7594172.png)

版本v0.1.4-dev

**Comment by Clash-Mini** [comment]
已知问题，待修复

**Comment by Clash-Mini** [comment]
@sephiroth945 已修复
