### ISSUE TITLE
关于win10系统下Dashboard白屏

### ISSUE THREAD

**Issue by GizmoOAO** [Clash-Mini/Clash.Mini#30]
I ❤ Microsoft :)
https://github.com/golang/go/issues/32350

也许添加下 `.js` 的 mime 会好使

```go
_ = mime.AddExtensionType(".js", "application/javascript")
```

**Comment by Clash-Mini** [comment]
> I ❤ Microsoft :) [golang/go#32350](https://github.com/golang/go/issues/32350)
> 
> 也许添加下 `.js` 的 mime 会好使
> 
> ```go
> _ = mime.AddExtensionType(".js", "application/javascript")
> ```

谢谢，我抽空测试下
