### ISSUE TITLE
怎么添加vless节点呢？

### ISSUE THREAD

**Issue by kSirZX** [Clash-Mini/Clash.Mini#31]
怎么添加vless节点呢？

**Comment by Clash-Mini** [comment]
proxies:
  - name: "vless-tcp"
    type: vless
    server: server
    port: 443
    uuid: uuid
    network: tcp
    servername: example.com # AKA SNI
    # flow: xtls-rprx-direct # xtls-rprx-origin  # enable XTLS
    # skip-cert-verify: true
    
  - name: "vless-ws"
    type: vless
    server: server
    port: 443
    uuid: uuid
    udp: true
    network: ws
    servername: example.com # priority over wss host
    # skip-cert-verify: true
    ws-path: /path
    ws-headers:
      Host: example.com

**Comment by kSirZX** [comment]
> ```
> proxies:
>   - name: "vless-tcp"
>     type: vless
>     server: server
>     port: 443
>     uuid: uuid
>     network: tcp
>     servername: [example.com](http://example.com) # AKA SNI
>      # flow: xtls-rprx-direct # xtls-rprx-origin  # enable XTLS
>      # skip-cert-verify: true
>     
>   - name: "vless-ws"
>     type: vless
>     server: server
>     port: 443
>     uuid: uuid
>     udp: true
>     network: ws
>     servername: [example.com](http://example.com) # priority over wss host
>      # skip-cert-verify: true
>     ws-path: /path
>     ws-headers:
>       Host: [example.com](http://example.com)
> ```

怎么添加呢？？？？？？配置放在哪里呢

**Comment by Clash-Mini** [comment]
用户配置，.core/profile
当前配置，目录下config.yaml

**Comment by kSirZX** [comment]
> 用户配置，.core/profile 当前配置，目录下config.yaml

搞定 3Q

**Comment by git10135405** [comment]
@kSirZX 请教下 支持quci协议吗 如以下vless怎么配置
vless://f4f2ff28-2c22-1455-0000-a2d219a096a0@http.cloudns.as:39010?type=quic&quicSecurity=chacha20-poly1305&key=lj02Fv&headerType=wireguard&security=none#43209-w8sy6o1f
