### ISSUE TITLE
支持rule-set吗？

### ISSUE THREAD

**Issue by iKingEast** [Clash-Mini/Clash.Mini#33]
比如
  🍎 Apple:
    behavior: classical
    type: http
    url: 'https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script/rule/Clash/Apple/Apple.yaml'
    interval: 3600
    path: ./Apple

**Comment by Clash-Mini** [comment]
@iKingEast 核心已经支持，下个版本mini实装

**Comment by Clash-Mini** [comment]
群组置顶dev版已经支持
