### ISSUE TITLE
WIN10无法打开控制面板

### ISSUE THREAD

**Issue by lichaoyangnice** [Clash-Mini/Clash.Mini#38]
V0.1.4版本，win10系统，右键客户端后选择“控制面板”，出现如图所示，显示崩溃。
![微信截图_20211206175450](https://user-images.githubusercontent.com/78831777/144825885-4bfd3739-4dd0-48e2-b88b-d5b4333169a2.png)

**Comment by Clash-Mini** [comment]
因为会调用chrome，你这个chrome是啥版本。

**Comment by lichaoyangnice** [comment]
是最新版的Chrome
![微信截图_20211207085358](https://user-images.githubusercontent.com/78831777/144946245-b0186592-3a89-41c5-8c1b-32bb83f59e4e.png)

**Comment by Clash-Mini** [comment]
@lichaoyangnice 请问下浏览器127.0.0.1:8070，面板能开启么

**Comment by lichaoyangnice** [comment]
可以开启的

**Comment by Clash-Mini** [comment]
@lichaoyangnice 请问用的什么版本，是在群里下载的0.1.5吗？

**Comment by lichaoyangnice** [comment]
在你github官方下载的Releases中V1.0.4版本，可以加群吗

**Comment by Clash-Mini** [comment]
@lichaoyangnice github介绍页有群组
