### ISSUE TITLE
win7 pro无法上网

### ISSUE THREAD

**Issue by magicmatt2020** [Clash-Mini/Clash.Mini#39]
win7 pro开启clash后，dashboard显示有流量但无法上网

**Comment by Clash-Mini** [comment]
@magicmatt2020 配置启用了吗？
系统代理开了吗？
如果是mixin模式，tun和dns有一起开吗？

**Comment by magicmatt2020** [comment]
解决了，系统时间没有同步，同步后正常了。

**Comment by Clash-Mini** [comment]
@magicmatt2020 啊这。。emmmmm
