### ISSUE TITLE
极客党大爱啊，我想提出点小小的建议，希望大佬可以参考下呢 

### ISSUE THREAD

**Issue by ldsoy** [Clash-Mini/Clash.Mini#4]
1.下载订阅的过程有点僵持，可以加入动画
2.有时候切换启用配置会卡顿
3.开启系统代理的时候，能不能改变小图标颜色
4.后续可不可以考虑自定义国内ip段的mmdb文件

**Comment by fxzxmicah** [comment]
@ldsoy tray都要砍了（逃

**Comment by fxzxmicah** [comment]
@ldsoy 右下角托盘（我瞎说的，别当真

**Comment by Mazeorz** [comment]
> 1.下载订阅的过程有点僵持，可以加入动画
> 2.有时候切换启用配置会卡顿
> 3.开启系统代理的时候，能不能改变小图标颜色
> 4.后续可不可以考虑自定义国内ip段的mmdb文件

1.倒是可以把按钮改成 下载中 的字样
2.切换配置是写入配置再推送至控制口，所以稍微有一丢丢卡顿感。得研究下怎么优化
3.图标问题可以变，不过没设计好一套合适的。
4.有打算新增自定义mmdb选择

**Comment by ldsoy** [comment]
> > 1.下载订阅的过程有点僵持，可以加入动画
> > 2.有时候切换启用配置会卡顿
> > 3.开启系统代理的时候，能不能改变小图标颜色
> > 4.后续可不可以考虑自定义国内ip段的mmdb文件
> 
> 1.倒是可以把按钮改成 下载中 的字样
> 2.切换配置是写入配置再推送至控制口，所以稍微有一丢丢卡顿感。得研究下怎么优化
> 3.图标问题可以变，不过没设计好一套合适的。
> 4.有打算新增自定义mmdb选择

爱了呀
[![BYfByM.png](https://www.helloimg.com/images/2021/05/20/BYfByM.png)](https://www.helloimg.com/image/BYfByM)
