### ISSUE TITLE
程序无法正常启动（闪退）

### ISSUE THREAD

**Issue by QieSen** [Clash-Mini/Clash.Mini#69]
解压后双击运行但无任何显示，在任务管理器中能看到进程运行一秒左右随即退出，将订阅文件 config.yaml 放置在目录中再运行问题依旧。

发布版本：Clash.Mini_v0.2.0_x64.7z

操作系统：ltsc 1809 build 17763.2928，已安装chromium edge、webview2

**Comment by MetaCubeX** [comment]
@vlcheng 看log

**Comment by QieSen** [comment]
> @vlcheng 看log

目录下没有生成日志文件，有其他查看方法吗？

另外我刚刚发现32bit版本能够正常运行🤔

**Comment by MetaCubeX** [comment]
@vlcheng 好的，问题已记录

**Comment by QieSen** [comment]
问题已解决，CPU较老不支持 [GOAMD64=v3](https://golang.org/wiki/MinimumRequirements#amd64)  所要求的指令集，使用32bit即可。
