### ISSUE TITLE
两个咨询？

### ISSUE THREAD

**Issue by ghost** [Clash-Mini/Clash.Mini#71]
1、只开tun，不开系统代理不能用吗？
  
   
2、“系统代理”和 其他设置的中的“默认系统代理”  有什么区别？

**Comment by MetaCubeX** [comment]
1. 开tun，可以不开系统代理
2. 默认系统代理的意思是，每次开启自动设置系统代理

**Comment by ghost** [comment]
那我只开tun，不开系统代理无法使用。这个问题，需要怎么排查？
